"""
String Utilities Module  
======================

Generated using mixed-model approach:
- Qwen backend for function generation
- Claude for coordination and integration

This module provides string formatting and validation utilities.
"""

import re
from typing import Optional, Union, List


class StringUtils:
    """String utility class with Qwen-generated functions"""
    
    @staticmethod
    def validate_email(email: str) -> bool:
        """
        Validates an email address using regex and returns boolean.
        
        Generated by Qwen backend via mixed-model approach.
        
        Args:
            email: Email address to validate
            
        Returns:
            bool: True if valid email, False otherwise
            
        Examples:
            >>> StringUtils.validate_email("user@example.com")
            True
            >>> StringUtils.validate_email("invalid-email")
            False
        """
        if not email or not isinstance(email, str):
            return False
            
        # RFC 5322 compliant regex pattern (simplified)
        pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        
        try:
            return bool(re.match(pattern, email.strip()))
        except Exception:
            return False
    
    @staticmethod
    def smart_truncate(text: str, max_length: int = 100, suffix: str = "...") -> str:
        """
        Truncates a string at word boundaries with ellipsis.
        
        Generated by Qwen backend via mixed-model approach.
        
        Args:
            text: Text to truncate
            max_length: Maximum length including suffix
            suffix: Suffix to add when truncating
            
        Returns:
            str: Truncated text with suffix if needed
            
        Examples:
            >>> StringUtils.smart_truncate("Hello world this is a test", 15)
            'Hello world...'
            >>> StringUtils.smart_truncate("Short", 100)
            'Short'
        """
        if not text or not isinstance(text, str):
            return ""
            
        if len(text) <= max_length:
            return text
            
        # Calculate max content length (subtract suffix length)
        max_content = max_length - len(suffix)
        
        if max_content <= 0:
            return suffix[:max_length]
        
        # Find last space within max_content
        truncated = text[:max_content]
        last_space = truncated.rfind(' ')
        
        if last_space > 0:
            # Truncate at word boundary
            return truncated[:last_space] + suffix
        else:
            # No space found, truncate at character boundary
            return truncated + suffix
    
    @staticmethod
    def normalize_whitespace(text: str) -> str:
        """
        Normalizes whitespace in text (collapse multiple spaces, trim).
        
        Args:
            text: Text to normalize
            
        Returns:
            str: Text with normalized whitespace
        """
        if not text or not isinstance(text, str):
            return ""
            
        # Replace multiple whitespace with single space and strip
        return re.sub(r'\s+', ' ', text.strip())
    
    @staticmethod
    def to_snake_case(text: str) -> str:
        """
        Converts text to snake_case.
        
        Args:
            text: Text to convert
            
        Returns:
            str: Text in snake_case format
        """
        if not text or not isinstance(text, str):
            return ""
            
        # Handle camelCase and PascalCase
        text = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', text)
        # Replace spaces and special chars with underscores
        text = re.sub(r'[^a-zA-Z0-9_]', '_', text)
        # Remove multiple underscores
        text = re.sub(r'_+', '_', text)
        # Strip leading/trailing underscores and convert to lowercase
        return text.strip('_').lower()
    
    @staticmethod
    def extract_numbers(text: str) -> List[float]:
        """
        Extracts all numbers from text.
        
        Args:
            text: Text to extract numbers from
            
        Returns:
            List[float]: List of extracted numbers
        """
        if not text or not isinstance(text, str):
            return []
            
        # Find all number patterns (including decimals)
        pattern = r'-?\d+\.?\d*'
        matches = re.findall(pattern, text)
        
        numbers = []
        for match in matches:
            try:
                # Convert to float if it contains decimal point, otherwise int
                if '.' in match:
                    numbers.append(float(match))
                else:
                    numbers.append(float(int(match)))
            except ValueError:
                continue
                
        return numbers