#!/usr/bin/env python3
"""
Mixed-Model Utility Library - Usage Examples
============================================

Demonstrates practical usage of the utility library created with:
- Qwen backend for code generation
- Claude for coordination and architecture

This showcases real-world applications of the mixed-model approach.
"""

import sys
import os
import tempfile
import json
from pathlib import Path

# Add current directory to path for imports
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from file_utils import FileUtils
from string_utils import StringUtils
from data_utils import DataUtils


def example_file_operations():
    """Demonstrate file utility functions generated by Qwen"""
    print("📁 File Operations Example (Qwen-generated functions)")
    print("-" * 50)
    
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        
        # Example 1: Safe file writing and reading
        config_file = temp_path / "app_config.txt"
        config_content = """
# Application Configuration
app_name = MyAwesomeApp
version = 1.0.0
debug = true
        """.strip()
        
        print("1. Writing configuration file...")
        success = FileUtils.atomic_write(config_file, config_content)
        print(f"   ✅ Write successful: {success}")
        
        print("2. Reading configuration file...")
        content = FileUtils.safe_read_text(config_file)
        print(f"   📄 Content preview: {content[:50]}...")
        
        # Example 2: Safe file copying
        backup_file = temp_path / "app_config_backup.txt"
        print("3. Creating backup...")
        copy_success = FileUtils.copy_file_safe(config_file, backup_file)
        print(f"   ✅ Backup created: {copy_success}")
        
        # Example 3: Handling missing files gracefully
        print("4. Reading non-existent file...")
        missing_content = FileUtils.safe_read_text(
            temp_path / "missing.txt", 
            default="Default configuration loaded"
        )
        print(f"   📄 Default content: {missing_content}")


def example_string_processing():
    """Demonstrate string utility functions generated by Qwen"""
    print("\n🔤 String Processing Example (Qwen-generated functions)")
    print("-" * 50)
    
    # Example 1: Email validation
    print("1. Email validation...")
    test_emails = [
        "user@example.com",
        "invalid-email",
        "test.email+tag@domain.org",
        "@missing-user.com"
    ]
    
    for email in test_emails:
        is_valid = StringUtils.validate_email(email)
        status = "✅ VALID" if is_valid else "❌ INVALID"
        print(f"   {email:25} → {status}")
    
    # Example 2: Smart text truncation
    print("\n2. Smart text truncation...")
    long_text = "This is a very long sentence that needs to be truncated intelligently at word boundaries"
    
    for length in [30, 50, 20]:
        truncated = StringUtils.smart_truncate(long_text, length)
        print(f"   Length {length:2}: {truncated}")
    
    # Example 3: Text normalization
    print("\n3. Text normalization...")
    messy_texts = [
        "  Multiple   spaces   everywhere  ",
        "Mixed\t\ttabs\nand\r\nnewlines",
        "CamelCaseVariable",
        "Text with 123 numbers and $pecial chars!"
    ]
    
    for text in messy_texts:
        normalized = StringUtils.normalize_whitespace(text)
        snake_case = StringUtils.to_snake_case(text)
        numbers = StringUtils.extract_numbers(text)
        
        print(f"   Original: {text[:30]}")
        print(f"   Normalized: {normalized}")
        print(f"   Snake case: {snake_case}")
        print(f"   Numbers: {numbers}")
        print()


def example_data_processing():
    """Demonstrate data utility functions generated by Qwen"""
    print("📊 Data Processing Example (Qwen-generated functions)")
    print("-" * 50)
    
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        
        # Example 1: JSON data handling
        print("1. JSON data operations...")
        
        app_data = {
            "users": [
                {"id": 1, "name": "Alice", "role": "admin"},
                {"id": 2, "name": "Bob", "role": "user"}
            ],
            "settings": {
                "theme": "dark",
                "notifications": True
            },
            "version": "1.0.0"
        }
        
        json_file = temp_path / "app_data.json"
        save_success = DataUtils.safe_json_save(app_data, json_file)
        print(f"   ✅ JSON saved: {save_success}")
        
        loaded_data = DataUtils.safe_json_load(json_file)
        print(f"   📄 Loaded {len(loaded_data['users'])} users")
        
        # Example 2: CSV data processing
        print("\n2. CSV data operations...")
        
        user_data = [
            {"name": "Alice", "age": "30", "department": "Engineering", "salary": "85000"},
            {"name": "Bob", "age": "25", "department": "Marketing", "salary": "65000"},
            {"name": "Charlie", "age": "35", "department": "Engineering", "salary": "95000"},
            {"name": "Diana", "age": "28", "department": "Sales", "salary": "70000"}
        ]
        
        csv_file = temp_path / "employees.csv"
        csv_success = DataUtils.dict_to_csv(user_data, csv_file)
        print(f"   ✅ CSV saved: {csv_success}")
        
        loaded_csv = DataUtils.csv_to_dict(csv_file)
        print(f"   📄 Loaded {len(loaded_csv)} employee records")
        
        # Calculate average salary using loaded data
        salaries = [float(emp["salary"]) for emp in loaded_csv]
        avg_salary = sum(salaries) / len(salaries)
        print(f"   💰 Average salary: ${avg_salary:,.2f}")
        
        # Example 3: Data merging
        print("\n3. Configuration merging...")
        
        default_config = {
            "database": {
                "host": "localhost",
                "port": 5432,
                "timeout": 30
            },
            "logging": {
                "level": "INFO",
                "file": "app.log"
            }
        }
        
        user_config = {
            "database": {
                "host": "production.db.com",
                "ssl": True
            },
            "logging": {
                "level": "DEBUG"
            },
            "features": {
                "analytics": True
            }
        }
        
        merged_config = DataUtils.merge_dicts(default_config, user_config, deep=True)
        print(f"   🔗 Merged config keys: {list(merged_config.keys())}")
        print(f"   🗄️  Database host: {merged_config['database']['host']}")
        print(f"   📝 Logging level: {merged_config['logging']['level']}")


def demonstrate_mixed_model_benefits():
    """Show the benefits of the mixed-model approach"""
    print("\n🚀 Mixed-Model Approach Benefits")
    print("=" * 50)
    
    print("🧠 Claude's Contributions:")
    print("   • 🏗️  Architectural design and coordination")
    print("   • 🔗 Integration and error handling")
    print("   • 🧪 Comprehensive testing strategy")
    print("   • 📚 Documentation and examples")
    print("   • 🔄 Workflow orchestration")
    
    print("\n🤖 Qwen's Contributions:")
    print("   • ⚡ Fast code generation")
    print("   • 🎯 Specialized utility functions")
    print("   • 🔧 Implementation details")
    print("   • 💡 Creative problem-solving")
    print("   • 🚀 Rapid prototyping")
    
    print("\n🤝 Combined Strengths:")
    print("   • 📈 Higher quality code (Claude review + Qwen generation)")
    print("   • ⚡ Faster development (parallel processing)")
    print("   • 🛡️  Better error handling (Claude oversight)")
    print("   • 🧪 Comprehensive testing (Claude coordination)")
    print("   • 📖 Better documentation (Claude expertise)")
    
    print("\n💡 Use Cases for Mixed-Model:")
    print("   • 🏗️  Large-scale application development")
    print("   • 🔧 Utility library creation")
    print("   • 🧪 Test suite generation")
    print("   • 📊 Data processing pipelines")
    print("   • 🔄 API client implementations")


def main():
    """Run all examples and demonstrate mixed-model benefits"""
    print("🎯 Mixed-Model Utility Library - Practical Examples")
    print("=" * 60)
    print("Demonstrating real-world usage of utilities generated by:")
    print("🤖 Qwen (code generation) + 🧠 Claude (coordination)")
    print()
    
    try:
        example_file_operations()
        example_string_processing() 
        example_data_processing()
        demonstrate_mixed_model_benefits()
        
        print("\n🎉 All examples completed successfully!")
        print("✅ Mixed-model approach delivers practical, tested utilities")
        
    except Exception as e:
        print(f"\n❌ Example failed: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()