"""
Ollama Backend Plugin for Claudette
Provides integration with local Ollama server
"""

import os
import requests
from typing import Dict, Any, List
from ..backends import BaseBackend


class OllamaBackend(BaseBackend):
    """Ollama local server backend"""
    
    name = "ollama"
    
    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.model = config.get('ollama_model') or os.getenv('OLLAMA_MODEL', 'llama2')
        self.base_url = config.get('ollama_url', 'http://localhost:11434')
        self.api_endpoint = f"{self.base_url}/api/generate"
    
    def send(self, prompt: str, cmd_args: List[str]) -> str:
        """Send prompt to Ollama server and return Claude-compatible response"""
        try:
            # Enhance prompt for command context
            enhanced_prompt = self._enhance_prompt_for_command(prompt, cmd_args)
            
            payload = {
                "model": self.model,
                "prompt": enhanced_prompt,
                "stream": False,
                "options": {
                    "temperature": 0.1,
                    "top_p": 0.9,
                    "max_tokens": 2000
                }
            }
            
            response = requests.post(
                self.api_endpoint,
                json=payload,
                timeout=60  # Ollama can be slow on first run
            )
            
            if response.status_code != 200:
                raise RuntimeError(f"Ollama server error {response.status_code}: {response.text}")
            
            result = response.json()
            content = result.get('response', '')
            
            if not content:
                raise RuntimeError("Empty response from Ollama server")
            
            # Format as Claude-compatible diff
            return self._format_as_diff(content, cmd_args)
            
        except requests.RequestException as e:
            raise RuntimeError(f"Ollama server request failed: {e}")
        except Exception as e:
            raise RuntimeError(f"Ollama backend error: {e}")
    
    def _enhance_prompt_for_command(self, prompt: str, cmd_args: List[str]) -> str:
        """Enhance prompt based on command arguments"""
        if not cmd_args:
            return prompt
        
        command = cmd_args[0] if cmd_args else "unknown"
        
        # Add system-like instruction for Ollama
        system_prompt = "You are a helpful coding assistant. Provide practical, actionable responses for development tasks.\n\n"
        
        if command == "edit":
            return f"{system_prompt}For file editing task: {prompt}\nProvide specific code changes or suggestions."
        elif command == "commit":
            return f"{system_prompt}For git commit: {prompt}\nSuggest commit message and changes summary."
        elif command == "new":
            return f"{system_prompt}For new project: {prompt}\nProvide project structure and initial code."
        
        return f"{system_prompt}{prompt}"
    
    def _format_as_diff(self, content: str, cmd_args: List[str]) -> str:
        """Format Ollama response as Claude-compatible diff"""
        command = cmd_args[0] if cmd_args else "unknown"
        
        # Clean up content (Ollama sometimes includes extra formatting)
        cleaned_content = content.strip()
        
        return f"""```diff
# Ollama Backend Response ({command} command)
+ {cleaned_content.replace(chr(10), chr(10) + '+ ')}
```

Note: Response generated by Ollama {self.model} backend"""
    
    def process(self, prompt: str, context: Dict[str, Any]) -> str:
        """Legacy process method for backwards compatibility"""
        return self.send(prompt, [])
    
    def is_available(self) -> bool:
        """Check if Ollama server is running and accessible"""
        try:
            # Check if Ollama server is running
            response = requests.get(
                f"{self.base_url}/api/tags",
                timeout=5
            )
            
            if response.status_code != 200:
                return False
            
            # Check if our model is available
            models = response.json().get('models', [])
            model_names = [model.get('name', '') for model in models]
            
            # Check for exact match or partial match (for different tags)
            return any(self.model in name for name in model_names)
            
        except Exception:
            return False