"""
Mistral Backend Plugin for Claudette
Provides integration with Mistral AI API
"""

import os
import requests
from typing import Dict, Any, List
from ..backends import BaseBackend


class MistralBackend(BaseBackend):
    """Mistral AI backend using their API"""
    
    name = "mistral"
    
    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.api_key = config.get('mistral_key') or os.getenv('MISTRAL_API_KEY')
        self.model = config.get('mistral_model', 'mistral-tiny')
        self.base_url = "https://api.mistral.ai/v1/chat/completions"
    
    def send(self, prompt: str, cmd_args: List[str]) -> str:
        """Send prompt to Mistral API and return Claude-compatible response"""
        if not self.api_key:
            raise RuntimeError("Mistral API key not configured. Set MISTRAL_API_KEY environment variable.")
        
        try:
            # Enhance prompt for command context
            enhanced_prompt = self._enhance_prompt_for_command(prompt, cmd_args)
            
            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json"
            }
            
            payload = {
                "model": self.model,
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a helpful coding assistant. Provide practical, actionable responses for development tasks."
                    },
                    {
                        "role": "user", 
                        "content": enhanced_prompt
                    }
                ],
                "max_tokens": 2000,
                "temperature": 0.1
            }
            
            response = requests.post(
                self.base_url,
                headers=headers,
                json=payload,
                timeout=30
            )
            
            if response.status_code != 200:
                raise RuntimeError(f"Mistral API error {response.status_code}: {response.text}")
            
            result = response.json()
            content = result['choices'][0]['message']['content']
            
            # Format as Claude-compatible diff
            return self._format_as_diff(content, cmd_args)
            
        except requests.RequestException as e:
            raise RuntimeError(f"Mistral API request failed: {e}")
        except Exception as e:
            raise RuntimeError(f"Mistral backend error: {e}")
    
    def _enhance_prompt_for_command(self, prompt: str, cmd_args: List[str]) -> str:
        """Enhance prompt based on command arguments"""
        if not cmd_args:
            return prompt
        
        command = cmd_args[0] if cmd_args else "unknown"
        
        if command == "edit":
            return f"For file editing task: {prompt}\nProvide specific code changes or suggestions."
        elif command == "commit":
            return f"For git commit: {prompt}\nSuggest commit message and changes summary."
        elif command == "new":
            return f"For new project: {prompt}\nProvide project structure and initial code."
        
        return prompt
    
    def _format_as_diff(self, content: str, cmd_args: List[str]) -> str:
        """Format Mistral response as Claude-compatible diff"""
        command = cmd_args[0] if cmd_args else "unknown"
        
        return f"""```diff
# Mistral Backend Response ({command} command)
+ {content.replace(chr(10), chr(10) + '+ ')}
```

Note: Response generated by Mistral {self.model} backend"""
    
    def process(self, prompt: str, context: Dict[str, Any]) -> str:
        """Legacy process method for backwards compatibility"""
        return self.send(prompt, [])
    
    def is_available(self) -> bool:
        """Check if Mistral API is configured and accessible"""
        if not self.api_key:
            return False
        
        try:
            # Quick ping to check API availability
            headers = {"Authorization": f"Bearer {self.api_key}"}
            response = requests.get(
                "https://api.mistral.ai/v1/models",
                headers=headers,
                timeout=5
            )
            return response.status_code == 200
        except Exception:
            return False