global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Claudette application metrics
  - job_name: 'claudette'
    static_configs:
      - targets: ['claudette:3000']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scheme: http
    
    # Add labels for better organization
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'claudette-app'
      - target_label: service
        replacement: 'claudette'
      - target_label: environment
        replacement: 'production'

  # Redis metrics (if using redis exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scheme: http
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting rules (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Sample alerting rules for Claudette
rule_files:
  - "claudette_alerts.yml"