name: 🤝 Community Contribution
description: Propose or discuss community-driven development initiatives
title: "[COMMUNITY] "
labels: ["community", "collaboration", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to Claudette Community Development! 🤝
        
        This template is for community-driven initiatives, collaboration proposals,
        and technical infrastructure improvements.

  - type: checkboxes
    id: search
    attributes:
      label: Community Guidelines
      description: Please confirm you understand our community approach
      options:
        - label: I have read the community guidelines and code of conduct
          required: true
        - label: This proposal focuses on technical collaboration (not marketing/social media)
          required: true
        - label: I understand this is for open source development contributions
          required: true

  - type: dropdown
    id: initiative-type
    attributes:
      label: Initiative Type
      description: What type of community initiative is this?
      options:
        - Development Environment Enhancement
        - Contributor Workflow Improvement
        - Technical Documentation
        - Code Review Process
        - Plugin Development Framework
        - Testing Infrastructure
        - Performance Benchmarking
        - API Documentation
        - Developer Tools
        - Other Technical Initiative
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Initiative Proposal
      description: Describe your community development proposal
      placeholder: |
        - What technical challenge or opportunity does this address?
        - How would this improve the contributor experience?
        - What infrastructure or tools would be involved?
        - How does this align with Claudette's technical roadmap?
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Project Scope
      description: What's the estimated scope of this initiative?
      options:
        - Small - Single script or tool enhancement
        - Medium - New workflow or documentation system
        - Large - Major infrastructure or framework
        - Epic - Multi-phase community platform
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: What technical components would be needed?
      placeholder: |
        Development Environment:
        - Docker containers, scripts, configurations
        
        Testing Infrastructure:
        - Automated validation, performance benchmarks
        
        Documentation Systems:
        - API generation, architecture docs, examples
        
        Developer Tools:
        - CLI enhancements, debugging tools, profiling
      render: markdown

  - type: checkboxes
    id: components
    attributes:
      label: Infrastructure Components
      description: Which technical components would this initiative involve?
      options:
        - label: Docker development environment
        - label: GitHub Actions workflows
        - label: TypeScript tooling and validation
        - label: Testing frameworks and automation
        - label: Documentation generation
        - label: API reference systems
        - label: Performance monitoring
        - label: Code quality tools
        - label: Plugin development SDK
        - label: Contributor validation tools

  - type: textarea
    id: implementation-plan
    attributes:
      label: Implementation Plan
      description: How would this initiative be implemented?
      placeholder: |
        Phase 1: Planning and Architecture
        - Technical design and specification
        - Community feedback and iteration
        
        Phase 2: Core Development
        - Build foundational components
        - Create testing infrastructure
        
        Phase 3: Integration and Documentation
        - Integrate with existing systems
        - Comprehensive documentation
        
        Phase 4: Community Adoption
        - Training materials and examples
        - Contributor onboarding
    validations:
      required: true

  - type: textarea
    id: collaboration-model
    attributes:
      label: Collaboration Model
      description: How would contributors collaborate on this initiative?
      placeholder: |
        - Lead maintainer or working group structure
        - Code review and approval process
        - Testing and validation requirements
        - Documentation standards
        - Community feedback mechanisms

  - type: dropdown
    id: skill-requirements
    attributes:
      label: Required Skills
      description: What technical skills would contributors need?
      multiple: true
      options:
        - TypeScript/Node.js development
        - Docker and containerization
        - GitHub Actions and CI/CD
        - Testing frameworks (Jest, etc.)
        - Documentation systems
        - API design and development
        - Performance optimization
        - Database and RAG systems
        - CLI tool development
        - Web development (for dashboards)

  - type: textarea
    id: success-metrics
    attributes:
      label: Success Metrics
      description: How would we measure the success of this initiative?
      placeholder: |
        Technical Metrics:
        - Reduced setup time for new contributors
        - Increased test coverage and quality
        - Faster validation and review cycles
        
        Community Metrics:
        - Number of active contributors
        - Quality of community contributions
        - Developer satisfaction scores
    validations:
      required: true

  - type: textarea
    id: resources-needed
    attributes:
      label: Resources Needed
      description: What resources or support would be helpful?
      placeholder: |
        Infrastructure:
        - Cloud services or hosting
        - CI/CD pipeline resources
        - Documentation hosting
        
        Human Resources:
        - Technical mentorship
        - Code review capacity
        - Community management support
        
        Tools and Services:
        - Development tools licenses
        - Third-party service integrations

  - type: checkboxes
    id: contribution-commitment
    attributes:
      label: Contribution Commitment
      description: What level of commitment can you make to this initiative?
      options:
        - label: I can lead this initiative and coordinate with other contributors
        - label: I can contribute significant development time
        - label: I can provide technical guidance and review
        - label: I can contribute specific expertise in my skill areas
        - label: I can help with testing and validation
        - label: I can assist with documentation and examples

  - type: textarea
    id: timeline
    attributes:
      label: Proposed Timeline
      description: What timeline do you envision for this initiative?
      placeholder: |
        Week 1-2: Community discussion and requirements gathering
        Week 3-4: Technical design and architecture planning
        Week 5-8: Core development and implementation
        Week 9-10: Testing, validation, and documentation
        Week 11-12: Community adoption and training materials

  - type: textarea
    id: alignment
    attributes:
      label: Roadmap Alignment
      description: How does this align with Claudette's current roadmap and priorities?
      placeholder: |
        - Supports Phase 2 community development objectives
        - Enhances contributor onboarding and collaboration
        - Improves technical infrastructure and tooling
        - Enables better code quality and testing
        - Facilitates plugin development and extensions
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: |
        - Related community initiatives or projects
        - Examples from other open source projects
        - Technical constraints or considerations
        - Integration with existing systems