name: ✨ Feature Request
description: Suggest a new feature or enhancement for Claudette
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        
        Please provide as much detail as possible to help us understand your needs.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: I have reviewed the roadmap to see if this is already planned
          required: true
        - label: This feature aligns with Claudette's core mission and architecture
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - AI Backend Integration (new provider)
        - RAG Enhancement (retrieval/vector databases)
        - Performance Optimization
        - Developer Experience
        - API/CLI Enhancement
        - Documentation/Tooling
        - Security/Authentication
        - Monitoring/Analytics
        - Plugin/Extension System
        - Community/Collaboration
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for adoption
        - Critical - Blocking current usage
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the current limitation or pain point:
        - What are you trying to achieve?
        - What's currently preventing you from doing this?
        - How does this impact your workflow?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        - What should the feature do?
        - How should it work?
        - What should the user experience be like?
        - Any technical considerations?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternatives have you considered?
      placeholder: |
        - Other ways to solve this problem
        - Existing tools or workarounds you've tried
        - Why those alternatives aren't sufficient

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        1. As a [developer/user], I want to [action] so that [benefit]
        2. When [scenario], I need [capability] to [outcome]
        3. This would enable [workflow/integration] that currently...
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Target Users
      description: Who would benefit from this feature?
      multiple: true
      options:
        - Individual developers
        - Development teams
        - Enterprise users
        - Open source contributors
        - AI researchers
        - DevOps engineers
        - Documentation writers
        - Plugin developers

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Implementation Ideas
      description: If you have technical ideas for implementation
      placeholder: |
        - Suggested architecture or approach
        - Integration points with existing code
        - Dependencies or requirements
        - Performance considerations
        - Backward compatibility concerns

  - type: textarea
    id: api-design
    attributes:
      label: API/Interface Design
      description: How should users interact with this feature?
      placeholder: |
        CLI commands:
        ```bash
        claudette new-feature --option value
        ```
        
        TypeScript API:
        ```typescript
        import { NewFeature } from 'claudette';
        const feature = new NewFeature(config);
        ```
        
        Configuration:
        ```json
        {
          "newFeature": {
            "enabled": true,
            "options": {}
          }
        }
        ```
      render: typescript

  - type: dropdown
    id: backend-support
    attributes:
      label: AI Backend Support
      description: Should this feature work with specific backends?
      multiple: true
      options:
        - All backends (universal)
        - OpenAI (GPT models)
        - Claude (Anthropic)
        - Qwen (CodeLLM)
        - Mistral
        - Ollama (Local)
        - Future backends
        - Backend-agnostic

  - type: dropdown
    id: rag-integration
    attributes:
      label: RAG Integration
      description: How should this feature integrate with RAG?
      options:
        - No RAG integration needed
        - Should work with existing RAG providers
        - Requires new RAG capabilities
        - RAG-specific feature
        - Should enhance RAG performance
        - Needs RAG configuration options

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete and working?
      placeholder: |
        - [ ] Feature can be enabled/disabled via configuration
        - [ ] Works with at least 2 AI backends
        - [ ] Includes comprehensive tests
        - [ ] Documentation is updated
        - [ ] Performance impact is minimal
        - [ ] Backward compatibility is maintained
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change, few files affected
        - Medium - Moderate change, some new components
        - Complex - Significant change, new architecture
        - Major - Large feature, substantial development
        - Unknown - Need technical assessment

  - type: textarea
    id: testing-strategy
    attributes:
      label: Testing Strategy
      description: How should this feature be tested?
      placeholder: |
        - Unit tests for core functionality
        - Integration tests with AI backends
        - RAG integration tests (if applicable)
        - Performance benchmarks
        - End-to-end user scenarios
        - Edge cases and error handling

  - type: textarea
    id: documentation
    attributes:
      label: Documentation Requirements
      description: What documentation would be needed?
      placeholder: |
        - API reference updates
        - User guide sections
        - Configuration examples
        - Troubleshooting guide
        - Migration guide (if needed)
        - Architecture documentation

  - type: textarea
    id: migration
    attributes:
      label: Migration Considerations
      description: Would this feature require any breaking changes or migrations?
      placeholder: |
        - Breaking changes to existing APIs
        - Configuration file updates needed
        - Database schema changes
        - Backward compatibility strategy
        - Migration tooling requirements

  - type: textarea
    id: related-work
    attributes:
      label: Related Work
      description: Links to related issues, discussions, or external resources
      placeholder: |
        - Related GitHub issues: #123, #456
        - Community discussions: [link]
        - Similar features in other tools: [examples]
        - Research papers or articles: [links]

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to implement this feature
        - label: I can help with design and planning
        - label: I can provide testing and feedback
        - label: I can help with documentation
        - label: I need guidance on how to contribute

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: |
        - Screenshots or mockups
        - Performance requirements
        - Security considerations
        - Regulatory compliance needs
        - Timeline constraints