"""
Data Utilities Module
====================

Generated using mixed-model approach:
- Qwen backend for function generation  
- Claude for coordination and integration

This module provides JSON/CSV processing utilities.
"""

import json
import csv
from pathlib import Path
from typing import Any, Dict, List, Optional, Union
import io


class DataUtils:
    """Data utility class with Qwen-generated functions"""
    
    @staticmethod
    def safe_json_load(file_path: Union[str, Path], default: Any = None) -> Any:
        """
        Loads JSON data with error handling and default values.
        
        Generated by Qwen backend via mixed-model approach.
        
        Args:
            file_path: Path to JSON file
            default: Default value to return on error
            
        Returns:
            Any: Parsed JSON data or default value
            
        Examples:
            >>> data = DataUtils.safe_json_load("config.json", {})
            >>> data = DataUtils.safe_json_load("data.json", [])
        """
        try:
            file_path = Path(file_path)
            
            if not file_path.exists():
                return default
                
            with open(file_path, 'r', encoding='utf-8') as f:
                return json.load(f)
                
        except (json.JSONDecodeError, OSError, IOError) as e:
            print(f"Warning: Could not load JSON from {file_path}: {e}")
            return default
    
    @staticmethod
    def safe_json_save(data: Any, file_path: Union[str, Path], indent: int = 2) -> bool:
        """
        Saves data to JSON file with error handling.
        
        Args:
            data: Data to save as JSON
            file_path: Path to save JSON file
            indent: JSON indentation
            
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            file_path = Path(file_path)
            file_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=indent, ensure_ascii=False)
            return True
            
        except (TypeError, OSError, IOError) as e:
            print(f"Error: Could not save JSON to {file_path}: {e}")
            return False
    
    @staticmethod
    def csv_to_dict(file_path: Union[str, Path], delimiter: str = ',') -> List[Dict[str, str]]:
        """
        Converts CSV file to list of dictionaries with proper typing.
        
        Generated by Qwen backend via mixed-model approach.
        
        Args:
            file_path: Path to CSV file
            delimiter: CSV delimiter character
            
        Returns:
            List[Dict[str, str]]: List of dictionaries representing CSV rows
            
        Examples:
            >>> data = DataUtils.csv_to_dict("data.csv")
            >>> data = DataUtils.csv_to_dict("data.tsv", delimiter="\t")
        """
        try:
            file_path = Path(file_path)
            
            if not file_path.exists():
                return []
            
            result = []
            with open(file_path, 'r', encoding='utf-8', newline='') as f:
                reader = csv.DictReader(f, delimiter=delimiter)
                for row in reader:
                    # Convert OrderedDict to regular dict and handle None values
                    clean_row = {k: v if v is not None else "" for k, v in row.items()}
                    result.append(clean_row)
            
            return result
            
        except (OSError, IOError, csv.Error) as e:
            print(f"Error: Could not read CSV from {file_path}: {e}")
            return []
    
    @staticmethod
    def dict_to_csv(data: List[Dict[str, Any]], file_path: Union[str, Path], delimiter: str = ',') -> bool:
        """
        Saves list of dictionaries to CSV file.
        
        Args:
            data: List of dictionaries to save
            file_path: Path to save CSV file
            delimiter: CSV delimiter character
            
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            if not data:
                return False
                
            file_path = Path(file_path)
            file_path.parent.mkdir(parents=True, exist_ok=True)
            
            # Get all unique keys from all dictionaries
            fieldnames = set()
            for row in data:
                fieldnames.update(row.keys())
            fieldnames = sorted(fieldnames)
            
            with open(file_path, 'w', encoding='utf-8', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter=delimiter)
                writer.writeheader()
                writer.writerows(data)
            
            return True
            
        except (OSError, IOError, csv.Error) as e:
            print(f"Error: Could not write CSV to {file_path}: {e}")
            return False
    
    @staticmethod
    def merge_dicts(dict1: Dict[str, Any], dict2: Dict[str, Any], deep: bool = True) -> Dict[str, Any]:
        """
        Merges two dictionaries with optional deep merging.
        
        Args:
            dict1: First dictionary
            dict2: Second dictionary (takes precedence)
            deep: Whether to perform deep merge for nested dicts
            
        Returns:
            Dict[str, Any]: Merged dictionary
        """
        if not isinstance(dict1, dict) or not isinstance(dict2, dict):
            return dict2 if isinstance(dict2, dict) else dict1
        
        result = dict1.copy()
        
        for key, value in dict2.items():
            if deep and key in result and isinstance(result[key], dict) and isinstance(value, dict):
                result[key] = DataUtils.merge_dicts(result[key], value, deep=True)
            else:
                result[key] = value
        
        return result