"""
File Utilities Module
====================

Generated using mixed-model approach:
- Qwen backend for function generation
- Claude for coordination and integration

This module provides safe file operations with proper error handling.
"""

from pathlib import Path
from typing import Optional, Union, Dict, Any
import os
import tempfile
import shutil
try:
    import chardet
except ImportError:
    chardet = None


class FileUtils:
    """File utility class with Qwen-generated functions"""
    
    @staticmethod
    def safe_read_text(file_path: Union[str, Path], encoding: Optional[str] = None, default: str = "") -> str:
        """
        Reads a text file safely with encoding detection and error handling.
        
        Generated by Qwen backend via mixed-model approach.
        
        Args:
            file_path: Path to the file to read
            encoding: Optional encoding (auto-detected if None)
            default: Default value to return on error
            
        Returns:
            str: File contents or default value
            
        Examples:
            >>> content = FileUtils.safe_read_text("example.txt")
            >>> content = FileUtils.safe_read_text("data.txt", encoding="utf-8")
        """
        try:
            file_path = Path(file_path)
            
            if not file_path.exists():
                return default
                
            # Auto-detect encoding if not provided
            if encoding is None:
                if chardet is not None:
                    with open(file_path, 'rb') as f:
                        raw_data = f.read()
                        detected = chardet.detect(raw_data)
                        encoding = detected.get('encoding', 'utf-8')
                else:
                    encoding = 'utf-8'  # Fallback if chardet not available
            
            with open(file_path, 'r', encoding=encoding) as f:
                return f.read()
                
        except (OSError, IOError, UnicodeDecodeError) as e:
            print(f"Warning: Could not read {file_path}: {e}")
            return default
    
    @staticmethod
    def atomic_write(file_path: Union[str, Path], content: str, encoding: str = 'utf-8') -> bool:
        """
        Writes content to a file atomically to prevent corruption.
        
        Generated by Qwen backend via mixed-model approach.
        
        Args:
            file_path: Path to the file to write
            content: Content to write
            encoding: Text encoding
            
        Returns:
            bool: True if successful, False otherwise
            
        Examples:
            >>> success = FileUtils.atomic_write("output.txt", "Hello World")
            >>> success = FileUtils.atomic_write("data.json", json_content)
        """
        try:
            file_path = Path(file_path)
            file_path.parent.mkdir(parents=True, exist_ok=True)
            
            # Write to temporary file first
            with tempfile.NamedTemporaryFile(
                mode='w', 
                encoding=encoding, 
                dir=file_path.parent,
                delete=False
            ) as temp_file:
                temp_file.write(content)
                temp_path = temp_file.name
            
            # Atomically move to final location
            shutil.move(temp_path, file_path)
            return True
            
        except (OSError, IOError) as e:
            print(f"Error: Could not write {file_path}: {e}")
            # Clean up temp file if it exists
            if 'temp_path' in locals() and os.path.exists(temp_path):
                os.unlink(temp_path)
            return False
    
    @staticmethod
    def copy_file_safe(src: Union[str, Path], dst: Union[str, Path], overwrite: bool = False) -> bool:
        """
        Safely copy a file with error handling.
        
        Args:
            src: Source file path
            dst: Destination file path  
            overwrite: Whether to overwrite existing files
            
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            src_path = Path(src)
            dst_path = Path(dst)
            
            if not src_path.exists():
                print(f"Error: Source file {src_path} does not exist")
                return False
                
            if dst_path.exists() and not overwrite:
                print(f"Error: Destination {dst_path} exists and overwrite=False")
                return False
            
            dst_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_path, dst_path)
            return True
            
        except (OSError, IOError) as e:
            print(f"Error: Could not copy {src} to {dst}: {e}")
            return False