#!/usr/bin/env python3
"""
Mixed-Model Utility Library Tests
=================================

Tests for the utility library created using mixed-model approach:
- Qwen backend for code generation
- Claude for coordination and integration

This demonstrates the effectiveness of combining multiple LLMs.
"""

import sys
import os
import tempfile
import json
from pathlib import Path

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from file_utils import FileUtils
from string_utils import StringUtils
from data_utils import DataUtils


def test_file_utils():
    """Test file utility functions generated by Qwen"""
    print("🧪 Testing File Utils (Qwen-generated)")
    
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        test_file = temp_path / "test.txt"
        
        # Test atomic write
        success = FileUtils.atomic_write(test_file, "Hello, World!")
        assert success, "Atomic write should succeed"
        print("  ✅ atomic_write: SUCCESS")
        
        # Test safe read
        content = FileUtils.safe_read_text(test_file)
        assert content == "Hello, World!", f"Expected 'Hello, World!', got '{content}'"
        print("  ✅ safe_read_text: SUCCESS")
        
        # Test reading non-existent file
        missing_content = FileUtils.safe_read_text(temp_path / "missing.txt", default="DEFAULT")
        assert missing_content == "DEFAULT", "Should return default for missing file"
        print("  ✅ safe_read_text (missing file): SUCCESS")
        
        # Test file copy
        copy_file = temp_path / "copy.txt"
        copy_success = FileUtils.copy_file_safe(test_file, copy_file)
        assert copy_success, "File copy should succeed"
        assert copy_file.exists(), "Copy file should exist"
        print("  ✅ copy_file_safe: SUCCESS")
    
    print("  🎯 All file utils tests passed!")


def test_string_utils():
    """Test string utility functions generated by Qwen"""
    print("\n🧪 Testing String Utils (Qwen-generated)")
    
    # Test email validation
    valid_emails = ["user@example.com", "test.email+tag@domain.org", "simple@test.co.uk"]
    invalid_emails = ["invalid", "@domain.com", "user@", "user.domain", ""]
    
    for email in valid_emails:
        assert StringUtils.validate_email(email), f"Should validate {email}"
    
    for email in invalid_emails:
        assert not StringUtils.validate_email(email), f"Should reject {email}"
    
    print("  ✅ validate_email: SUCCESS")
    
    # Test smart truncate
    text = "This is a long sentence that should be truncated properly"
    truncated = StringUtils.smart_truncate(text, 25)
    assert len(truncated) <= 25, "Truncated text should be within limit"
    assert truncated.endswith("..."), "Should end with ellipsis"
    assert "sentence" not in truncated, "Should not truncate mid-word"
    print("  ✅ smart_truncate: SUCCESS")
    
    # Test whitespace normalization
    messy_text = "  Multiple   spaces\t\nand   newlines  "
    normalized = StringUtils.normalize_whitespace(messy_text)
    assert normalized == "Multiple spaces and newlines", f"Got: '{normalized}'"
    print("  ✅ normalize_whitespace: SUCCESS")
    
    # Test snake case conversion
    camel_case = "myVariableName"
    snake_case = StringUtils.to_snake_case(camel_case)
    assert snake_case == "my_variable_name", f"Got: '{snake_case}'"
    print("  ✅ to_snake_case: SUCCESS")
    
    # Test number extraction
    text_with_numbers = "Price: $19.99, Quantity: 5, Discount: -2.5%"
    numbers = StringUtils.extract_numbers(text_with_numbers)
    expected = [19.99, 5.0, -2.5]
    assert numbers == expected, f"Expected {expected}, got {numbers}"
    print("  ✅ extract_numbers: SUCCESS")
    
    print("  🎯 All string utils tests passed!")


def test_data_utils():
    """Test data utility functions generated by Qwen"""
    print("\n🧪 Testing Data Utils (Qwen-generated)")
    
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        
        # Test JSON operations
        test_data = {"name": "test", "values": [1, 2, 3], "nested": {"key": "value"}}
        json_file = temp_path / "test.json"
        
        # Test JSON save
        success = DataUtils.safe_json_save(test_data, json_file)
        assert success, "JSON save should succeed"
        print("  ✅ safe_json_save: SUCCESS")
        
        # Test JSON load
        loaded_data = DataUtils.safe_json_load(json_file)
        assert loaded_data == test_data, "Loaded data should match saved data"
        print("  ✅ safe_json_load: SUCCESS")
        
        # Test loading missing JSON file
        missing_data = DataUtils.safe_json_load(temp_path / "missing.json", default={})
        assert missing_data == {}, "Should return default for missing file"
        print("  ✅ safe_json_load (missing file): SUCCESS")
        
        # Test CSV operations
        csv_data = [
            {"name": "Alice", "age": "30", "city": "New York"},
            {"name": "Bob", "age": "25", "city": "Los Angeles"},
            {"name": "Charlie", "age": "35", "city": "Chicago"}
        ]
        csv_file = temp_path / "test.csv"
        
        # Test CSV save
        csv_success = DataUtils.dict_to_csv(csv_data, csv_file)
        assert csv_success, "CSV save should succeed"
        print("  ✅ dict_to_csv: SUCCESS")
        
        # Test CSV load
        loaded_csv = DataUtils.csv_to_dict(csv_file)
        assert len(loaded_csv) == 3, "Should load 3 rows"
        assert loaded_csv[0]["name"] == "Alice", "First row name should be Alice"
        print("  ✅ csv_to_dict: SUCCESS")
        
        # Test dict merging
        dict1 = {"a": 1, "b": {"x": 10}}
        dict2 = {"b": {"y": 20}, "c": 3}
        merged = DataUtils.merge_dicts(dict1, dict2, deep=True)
        expected = {"a": 1, "b": {"x": 10, "y": 20}, "c": 3}
        assert merged == expected, f"Expected {expected}, got {merged}"
        print("  ✅ merge_dicts: SUCCESS")
    
    print("  🎯 All data utils tests passed!")


def main():
    """Run all tests and demonstrate mixed-model approach"""
    print("🚀 Mixed-Model Utility Library Test Suite")
    print("=" * 50)
    print("🧠 Claude: Coordinating comprehensive testing")
    print("🤖 Qwen: Generated utility functions being tested")
    print()
    
    try:
        test_file_utils()
        test_string_utils()
        test_data_utils()
        
        print("\n🎉 Mixed-Model Development SUCCESS!")
        print("=" * 40)
        print("✅ All tests passed")
        print("✅ Qwen successfully generated utility functions")
        print("✅ Claude successfully coordinated integration")
        print("✅ Mixed-model approach validated")
        
        # Performance summary
        print("\n📊 Mixed-Model Approach Benefits:")
        print("  • Qwen: Specialized in code generation")
        print("  • Claude: Excellent at coordination & integration")
        print("  • Combined: Leverages strengths of both models")
        print("  • Result: High-quality, well-tested utility library")
        
        return True
        
    except Exception as e:
        print(f"\n❌ Test failed: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)